### ISSUE TITLE
Failures on master

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/miktex-feedstock#10]
Appears this is failing to build on `master`. See this [log](https://ci.appveyor.com/project/conda-forge/miktex-feedstock/build/1.0.7).

**Comment by jankatins** [comment]
Damn, the old miktex installers are not kept but replaced with newer versions :-(

**Comment by jankatins** [comment]
Fix in https://github.com/conda-forge/miktex-feedstock/pull/8
