### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ivoflipse** [conda-forge/miktex-feedstock#12]
I just ran into: http://miktex.org/howto/build-unx

Which indicates that it should be doable to build Miktex for Linux platforms as well. The build steps seem reasonable, so it's mostly a matter of whether the dependencies are all available on conda-forge
- [ ] "MiKTeX Tools" is mostly written in C++. It should work with any ANSI-compliant C++ compiler.
- [x] CMake 2.8 (or newer) is required for building and installing "MiKTeX Tools".
- [x] The Qt development kit (version 4.8 or newer) is required, if you intend to enable GUI features (e.g., the auto-installer message box). A common name for this package is libqt4-devel.
- [ ] Lynx (text-based web browser) and xsltproc (XSLT processor) are required for building the reference pages.
- [ ] "MiKTeX Tools" depends on the availability of pthreads libraries and header files.
- [x] CURL libraries and header files are required. A common name for this package is libcurl-devel.
- [x] Expat libraries and header files are required. A common name for this package is libexpat-devel.
- [x] BZip2 libraries and header files are required. A common name for this package is libbz2-devel.
- [ ] UriParser libraries and header files are required. A common name for this package is liburiparser-devel.
- [x] zlib libraries and header files are required. A common name for this package is zlib-devel.
- [x] PNG libraries and header files are required. A common name for this package is libpng-devel.

**Comment by Korijn** [comment]
- https://github.com/conda-forge/libpng-feedstock
- https://github.com/conda-forge/cmake-feedstock
- https://github.com/conda-forge/qt-feedstock

Looks like there are a few more boxes you can tick?
