### ISSUE TITLE
Recipe fails because the portable version is deprecated and doesn't exist anymore

### ISSUE THREAD

**Issue by tadeu** [conda-forge/miktex-feedstock#22]
The `http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/miktex-portable-{{ version }}.exe` URL used in the recipe doesn't exist anymore (for version `2.9.6753` or any other version), and I couldn't find a [mirror/archived version elsewhere](https://tex.stackexchange.com/questions/527952/are-previous-releases-of-miktex-available), so the recipe can't be built from it anymore.

According to the MiKTeX site, [MiKTeX Portable was discontinued](https://miktex.org/announcement/miktex-portable-sfx-discontinued), but the basic installer may be used, renaming it to `miktex-portable.exe` or with the `--portable` flag.

**Comment by mbargull** [comment]
closed via gh-24
