### ISSUE TITLE
Attempts to install into a new virtual environment in anaconda fails

### ISSUE THREAD

**Issue by wdrennan** [conda-forge/miktex-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am trying to install miktex to an anaconda virtual environment, but using the built in package manager keeps failing. When I try using the cmd.exe prompt to run "conda install -c conda-forge miktex", I get the following error message:

(debugging_miktex) C:\Users\willi>conda install -c conda-forge miktex
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\willi\anaconda3\envs\debugging_miktex

  added / updated specs:
    - miktex

The following NEW packages will be INSTALLED:

  miktex             conda-forge/win-64::miktex-2.9.6753-h2fa13f4_1000

Proceed ([y]/n)? y

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(745): An error occurred while installing package 'conda-forge::miktex-2.9.6753-h2fa13f4_1000'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::miktex-2.9.6753-h2fa13f4_1000
location of failed script: C:\Users\willi\anaconda3\envs\debugging_miktex\Scripts\.miktex-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr:
Sorry, but "MiKTeX Package Manager" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/willi/AppData/Local/MiKTeX/2.9/miktex/log/mpmcli.log

You may want to visit the MiKTeX project page, if you need help.

Sorry, but "MiKTeX Package Manager" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/willi/AppData/Local/MiKTeX/2.9/miktex/log/mpmcli.log

You may want to visit the MiKTeX project page, if you need help.

return code: 1

()

### Installed packages

```shell
# packages in environment at C:\Users\willi\anaconda3\envs\debugging_miktex:
#
# Name                    Version                   Build  Channel
certifi                   2020.6.20          pyhd3eb1b0_3
console_shortcut          0.1.1                         4
pip                       20.0.2                   py36_1    conda-forge
python                    3.6.15          h39d44d4_0_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
setuptools                49.6.0           py36ha15d459_3    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wheel                     0.34.2                   py36_0    conda-forge
wincertstore              0.2             pyhd8ed1ab_1009    conda-forge
```

### Environment info

```shell
active environment : debugging_miktex
    active env location : C:\Users\willi\anaconda3\envs\debugging_miktex
            shell level : 1
       user config file : C:\Users\willi\.condarc
 populated config files : C:\Users\willi\.condarc
          conda version : 23.1.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __win=0=0
       base environment : C:\Users\willi\anaconda3  (writable)
      conda av data dir : C:\Users\willi\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\willi\anaconda3\pkgs
                          C:\Users\willi\.conda\pkgs
                          C:\Users\willi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\willi\anaconda3\envs
                          C:\Users\willi\.conda\envs
                          C:\Users\willi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by tdegeus** [comment]
Same here https://github.com/conda-forge/doxygen-feedstock/pull/42
(I force pushed a skip, so the build is not preserved, but the error was identical)

**Comment by mbargull** [comment]
closed via gh-24
