### ISSUE TITLE
does not work with pandoc

### ISSUE THREAD

**Issue by jankatins** [conda-forge/miktex-feedstock#3]
pandoc expects *.exe files as pdflatex executable :-( https://github.com/jgm/pandoc/issues/2903

A workaround would be to remove the batch files and use a exe launcher, but for that I would need someone who can modify http://kettle.bleuel.com/2011/12/14/exebatlauncher-calling-bat-files-by-exe-executables-eg-having-a-spoonexe/ to include the full path instead of only changing `exe` to `bat`.

Or change this here: https://github.com/omasanori/luatex-mirror/tree/master/source/texk/texlive/w32_wrapper

**Comment by Korijn** [comment]
That's so silly. :/ at least the `miktex` package is perfectly usable for direct usage. :)

**Comment by jankatins** [comment]
Closes by #4
