### ISSUE TITLE
check if we do all the right things according to the manual

### ISSUE THREAD

**Issue by jankatins** [conda-forge/miktex-feedstock#6]
The manual: http://docs.miktex.org/manual/miktex-tools.html

-> There are some help content what to run on system and user installations. System parts should probably run at build time (but probably already are due to the portable installer) but the user part should probably become a post-install script.

**Comment by jankatins** [comment]
It might also be interesting to mention stuff like this:

```
# autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
# this adds this to the registry!
initexmf --set-config-value "[MPM]AutoInstall=1"
```

**Comment by ivoflipse** [comment]
I personally always found Miktex worked rather magical, but then again I didn't bother to check the documentation in detail either. Obviously duplicating everything across environments is rather wasteful, so having a system install would be useful, but I have no idea where it should be installed and how all the user installs in different environments will know where to find it

**Comment by jankatins** [comment]
Currently we install no additional packages into the system installation, so in theory all stuff should go into a per user installation path under the users home directory (`C:\Users\<USER>\AppData\Roaming\MiKTeX\` on win7). This should mean that installing miktex in each environment will not waste any space as it is hardlinked by conda.

On the other hand, it's enough to install miktex into the root env, the rest of the envs will have access to it, because conda keeps `<root>\Scripts` in the PATH...

The problem in this issue is more that any additional users which uses the environment will have `nbconvert` or any other latex using command work without running any additional commands (like updating the user package DB like we currently do for the user which installs the package).

**Comment by Korijn** [comment]
There's no way to pin packages within Miktex to a specific version anyway (I think there's only support for a "minimum release date"), so having all packages on one big heap makes sense to me.

**Comment by jankatins** [comment]
The next version will automatically install new latex packages into the user location.

**Comment by jankatins** [comment]
PR: https://github.com/conda-forge/miktex-feedstock/pull/11
